website/auth.py
import datetime
import io
import requests
from .models import userdetail, db, User, shows , Favourite, Live, AdminUser
from .forms import RegistrationForm, ChangePasswordForm, LiveUploadForm , ProfileForm, UploadForm
from datetime import datetime
from . import db
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, Response
from website import cv2
from flask_login import LoginManager, current_user, login_required
from flask import Blueprint, request, jsonify
import base64
from flask import request
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required



auth = Blueprint('auth', __name__)

def init_auth(app, cam):
    app.camera = cam   


def generate_frames():
    while True:
        success, frame = camera.read()
        if not success:
            break
        else:
            ret, buffer = cv2.imencode('.jpg', frame)

            # Check if the encoding was successful
            if ret:
                frame = buffer.tobytes()
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
            else:
                # Log or handle the error as needed
                print("Error encoding frame.")



auth = Blueprint('auth', __name__)
camera = None

def init_auth(app, cam):
    global camera
    camera = cam



                                               

@auth.route('/admin')
def admin():
    return render_template('admin.html')                            



@auth.route('/adminform')
def adminform():
    return render_template('adminform.html')

@auth.route('/admintable')
def admintable():
    users = User.query.all()
    # Unhash the passwords
    for user in users:
        unhashed_password = check_password_hash(user.password_hash, user.password_hash)
        user.password = unhashed_password
    return render_template('admintable.html', users=users)



@auth.route('/adminlogin', methods=['GET', 'POST'])
def adminlogin():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        
        user = AdminUser.query.filter_by(email=email).first()

        if user and user.check_password(password):
            # Set the user session
            session['user_id'] = user.id
            session['user_name'] = user.username 
            return redirect(url_for('auth.radmindashboard'))
            
        else:
            # If user doesn't exist or password is incorrect, show an alert
            flash('Invalid email or password. Please try again.', 'error')

    return render_template('adminlogin.html')


@auth.route('/live_upload', methods=['GET', 'POST'])
def live_upload():
    form = LiveUploadForm()
    if form.validate_on_submit():
        video_file = form.video.data
        new_live = Live(video=video_file.read())
        db.session.add(new_live)
        db.session.commit()
        return redirect(url_for('auth.live_upload'))
    return render_template('live_upload.html', form=form)



@auth.route('/live')
def live():
    user_id = session.get('user_id')
    user = User.query.get(user_id) if user_id else None
    active_tab = 'ongoing'
    upcoming_shows = shows.query.filter(shows.release > datetime.now()).all()
    previous_shows = shows.query.filter(shows.release < datetime.now()).all()
    live_shows = Live.query.all()
    return render_template('live.html', user=user, active_tab=active_tab, upcoming_shows=upcoming_shows, previous_shows=previous_shows, live_shows=live_shows)


@auth.route('/register.html', methods=['GET', 'POST'])
def register():
    print("Entered the register route.")
    form = RegistrationForm()

    if request.method == 'POST' and form.validate():
        print("Form is valid and submitted.")

        # Registration logic here
        email = form.email.data
        password = form.password.data
        name = form.name.data
        country = form.country.data   

        # Check if the email is already registered
        existing_user = User.query.filter_by(email=email).first()
        if existing_user:
            flash('Email is already registered', 'error')
            return redirect(url_for('auth.register'))

        # Create a new user
        new_user = User(email=email, name=name, country=country)
        new_user.set_password(password)

        # Save the user to the database
        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful. You can now log in.', 'success')
        return redirect(url_for('auth.login'))  # Corrected redirection

    else:
        print("Form validation errors:", form.errors)

    country_names = get_country_names()
    return render_template('register.html', form=form, country_names=country_names)

def get_country_names():
    api_endpoint = 'https://restcountries.com/v3.1/all'
    
    response = requests.get(api_endpoint)

    if response.status_code == 200:
        countries = response.json()
        country_names = [country['name']['common'] for country in countries]
        sorted_country_names = sorted(country_names)
        return sorted_country_names
    else:
        return []

@auth.route('/login', methods=['GET', 'POST'])
def loginn():
    if 'user_id' in session:
        # Fetch the user object from the database or use the stored information as needed
        user = User.query.get(session['user_id'])
        shows_data = shows.query.all()

        # Fetch saved shows for the current user from the database
        saved_shows = [fav.show_id for fav in Favourite.query.filter_by(user_id=user.id).all()]

        return render_template('index.html', user=user, shows_data=shows_data, saved_shows=saved_shows)

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        # Find the user by email
        user = User.query.filter_by(email=email).first()

        # Check if the user exists and the password is correct
        if user and user.check_password(password):
            # Set the user session
            session['user_id'] = user.id
            session['user_name'] = user.name 

            # Fetch shows data from the database
            shows_data = shows.query.all()

            # Fetch saved shows for the current user from the database
            saved_shows = [fav.show_id for fav in Favourite.query.filter_by(user_id=user.id).all()]

            # Render admin page with user and shows data
            return render_template('index.html', user=user, shows_data=shows_data, saved_shows=saved_shows)
        else:
            flash('Invalid email or password', 'error')

    return render_template('login.html')


@auth.route('/sports')

def sports():
    user_id = session.get('user_id')
    user = User.query.get(user_id) if user_id else None
    return render_template('sports.html', user=user)

@auth.route('/schedule')

def schedule():
    user_id = session.get('user_id')
    user = User.query.get(user_id) if user_id else None
    return render_template('schedule.html', user=user)

@auth.route('/highlights')
def highlights():
    user_id = session.get('user_id')
    user = User.query.get(user_id) if user_id else None
    return render_template('highlights.html', user=user)

@auth.route('auth/login.html')  # No need to include '/auth' in the route URL
def login():
    return render_template('login.html')

@auth.route('/index.html')  
def index():
    user_id = session.get('user_id')
    user = User.query.get(user_id) if user_id else None
    return render_template('index.html',user=user)

@auth.route('/changepassword')
def changepassword():
        user_id = session.get('user_id')
        user = User.query.get(user_id) if user_id else None
        return render_template('changepassword.html',user=user)

@auth.route('/radmindashboard')
def radmindashboard():
        user_id = session.get('user_id')
        user = User.query.get(user_id) if user_id else None
        return render_template('radmindashboard.html',user=user)



@auth.route('/firm', methods=['GET', 'POST'])
def firm():
    form = UploadForm()
    if form.validate_on_submit():
        try:
            title = form.title.data
            category = form.category.data
            release_date_str = form.releaseDate.data
            release_date = datetime.strptime(release_date_str, '%Y-%m-%d').date()
            language = form.language.data
            
            new_show = shows(
                title=title,
                category=category,
                release=release_date,
                language=language
            )

            db.session.add(new_show)
            db.session.commit()
            
            flash('Files uploaded successfully', 'success')
        except Exception as e:
            flash(f'Error uploading files: {str(e)}', 'error')
    
    return render_template('showupload.html', form=form)



@auth.route('/logout', methods=['GET'])
def logout():
    # Clear the user session
    session.clear()
    # Redirect the user to the login page or any other desired page
    return redirect(url_for('auth.login'))

@auth.route('/adminlogout')
def adminlogout():
    # Clear the session
    session.clear()
    # Redirect to the adminlogin page
    return redirect(url_for('auth.adminlogin'))

@auth.route('/resetuser', methods=['GET', 'POST'])
def resetuser():
    if request.method == 'POST':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if user:
            if request.form.get('save'):  # Check if the form is submitted to save changes
                # Update user data with the form values
                user.name = request.form.get('username')
                user.country = request.form.get('country')
                user.contact_number = request.form.get('phone-number')
                # Commit changes to the database
                db.session.commit()

website/views.py
from flask import Blueprint, render_template, session

from website.models import User


views = Blueprint('views', __name__)

@views.route('/')
def home():
    user_id = session.get('user_id')
    user = User.query.get(user_id) if user_id else None
    return render_template('/index.html', user=user)

@views.route('/login.html')
def login():
    return render_template('login.html')

website/templates/adminnav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin Homepage</title>
    <script src="/static/script.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <style>
      .message{
        z-index: 1000;
      }

      .user-detail{
        border: 1 px solid white;
        padding: 5px;
        margin-top: 10px;
        box-shadow: 5px;


      }

      .logout-link{
        color: black;
      }

    .hero{
        background-color: white;
            .logout-link{
        color: black;
      }
    }
    .hero:hover{
        background-color: black;
        .logout-link:hover{
            color: white;
        } 
    }
    </style>
</head>
<body>
 
<section class="secondsection">
  <div class="header video" id="header">
   

<div class="nav" id="navbar">
   
  <div class="logo">
    <a href="{{url_for('views.home')}}"><img src="/static/img/logo-removebg-preview.png"></a>
   </div>
  
   <div class="login-menu" id="loginMenu" style="z-index: 1500;">
    <ul>
        {% if user %}
        <div class="user-detail">
            <div style="padding-bottom: 10px;">
                <label>Email: <span class="strong">{{user.email}}</span></label>
            </div>
            <div style="padding-top: 10px;">
                <label>Password: <span class="strong">{{user.name}}</span></label>
            </div>
            <div class="hero">
            <hr style="margin-top: 25px;">
            <li><a href="{{ url_for('auth.adminlogout') }}" class="logout-link">Logout</a></li>
        </div>
    </div>
        {% else %}
            <li><a href="{{ url_for('auth.loginn') }}">Login</a></li>
        {% endif %}
        <hr>
       
        
        
    </ul>
</div>
  <div class="icon">
     
    <a href="#"><i class="fa-regular fa-user" id="loginIcon"></i></a>
  </div>
  <ol>
     
      <a href="{{url_for('auth.radmindashboard')}}"><li>Dashboard</li></a> 
      <a href="{{ url_for('auth.live_upload') }}"><li>Go live</li></a> 
      <a href="{{ url_for('auth.admintable') }}"><li>Manage User</li></a>
      <a href="{{ url_for('auth.firm') }}"><li>Upload Show</li></a>
      
  </ol>
</div> 


<div class="background-video">
  <video autoplay loop muted>
      <source src="/static/img/intro3.mp4" type="video/mp4">
     
  </video>
</div>

<div class="message">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}" id="flash-message">
          {{ message }}
          <span class="close-icon" onclick="hideMessage(this)">X</span>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>
{% block content %}
        
{% endblock %}


<script>
    function hideMessage(element) {
      element.parentElement.style.display = 'none';
    }
  </script>
  </body>
  </html>

website/templates/index.html
{% extends 'roshannav.html' %}
{% block title %} Homepage{% endblock %}
{% block content %}


<div class="background-video">
  <video autoplay loop muted>
      <source src="/static/img/intro3.mp4" type="video/mp4">
     
  </video>
</div>

<div class="message">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}" id="flash-message">
          {{ message }}
          <span class="close-icon" onclick="hideMessage(this)">X</span>
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
</div>

<div class="quotesvideo">

  <h4>Experience The Execlusive</h4>
  <h1><b>OLYMPIC GAMES PARIS 2024</b></h1>

</div>
<div class="countdown-container" id="countdown">
  <div class="picturea">
    <img src="/static/img/logo-removebg-preview.png">
  </div>
  <div class="textappear">
    Time left until the<br> Olympic Games Paris 2024
  </div>
  <div class="countdown-box">
      <div class="countdown-number" id="days">00</div>
      <div class="countdown-label">Days</div>
  </div>
  <div class="countdown-box">
      <div class="countdown-number" id="hours">00</div>
      <div class="countdown-label">Hours</div>
  </div>
  <div class="countdown-box">
      <div class="countdown-number" id="minutes">00</div>
      <div class="countdown-label">Minutes</div>
  </div>
  <div class="countdown-box">
      <div class="countdown-number" id="seconds">00</div>
      <div class="countdown-label">Seconds</div>
  </div>

</div>
</div>

</div>
</section>
<section class="some quotes">
  <div class="divaftersection" id="divaf">



</div>


  <!-- Add these buttons where you want to trigger the next and previous slides -->
<button id="prevButton" class="btn slideprev"><i class="fa-solid fa-backward"></i></button>
<button id="nextButton" class="btn slidenext"><i class="fa-solid fa-forward"></i></button>

<section class="listofticket">
  <div class="themeregister">
    <h1><span>Unleash</span> the <span> FunOlympic</span>  Spirit: <br>
      <a href=""><u>and</u></a> <span>Enjoy</span><br> <span>Ultimate </span> Online <span>Games </span>Experience!
    </h1>
  </div>

  {% if user %}
  <div class="registerbtn">
      <a href="{{url_for('auth.live')}}">
          <button type="submit" class="btn">Watch Live</button>
      </a>
  </div>
{% else %}
  <div class="registerbtn">
      <a href="{{ url_for('auth.register') }}"><button type="submit" class="btn">Register Now</button></a>
  </div>
{% endif %}
</section>





  <div class="carousel-wrapper">
    <div class="carousel-container">
      <!-- Repeat the following content-box structure for each item -->
      
      <div class="container">
        <div class="content-box">
          <div class="pro">
            <video width="100%" height="100%" controls>
              <source src="static/img/intro3.mp4" type="video/mp4">
            </video>
            <div class="des">
              <span>Premium combo package 4g</span>
              <h5>1 Month</h5>
              <div class="star">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <h4>Rs. 264/-</h4>
              <a href="{{url_for('auth.watchvideo')}}"><button type="submit" class="btnsmall">Watch Now</button></a>
            </div>
          </div>
        </div>
        <!-- End content-box -->

        <!-- Repeat the above content-box structure for each item -->
        <div class="container">
          <div class="content-box">
            <div class="pro">
              <video width="100%" height="100%" controls>
                <source src="static/img/intro3.mp4" type="video/mp4">
              </video>
              <div class="des">
                <span>Premium unlimited combo package</span>
                <h5>1 year</h5>
                <div class="star">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <h4>Rs.5896</h4>
                <a href="{{url_for('auth.watchvideo')}}"><button type="submit" class="btnsmall">Watch Now</button></a>
              </div>
            </div>
          </div>
          <!-- End content-box -->
                 <!-- Repeat the above content-box structure for each item -->
        <div class="container">
          <div class="content-box">
            <div class="pro">
              <video width="100%" height="100%" controls>
                <source src="static/img/intro3.mp4" type="video/mp4">
              </video>
              <div class="des">
                <span>Premium  1 day pack</span>
                <h5>24 hour</h5>
                <div class="star">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <h4>Rs. 29 lakh</h4>
                <a href=""><button type="submit" class="btnsmall">Watch Now</button></a>
              </div>
            </div>
          </div>
          <!-- End content-box -->
                 <!-- Repeat the above content-box structure for each item -->
        <div class="container">
          <div class="content-box">
            <div class="pro">
              <video width="100%" height="100%" controls>
                <source src="static/img/intro3.mp4" type="video/mp4">
              </video>
              <div class="des">
                <span>Premium  3 day pack</span>
                <h5>3 days</h5>
                <div class="star">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <h4>Rs. 296</h4>
                <a href="{{url_for('auth.watchvideo')}}"><button type="submit" class="btnsmall">Watch Now</button></a>
              </div>
            </div>
          </div>
          <!-- End content-box -->
                 <!-- Repeat the above content-box structure for each item -->
        <div class="container">
          <div class="content-box">
            <div class="pro">
              <video width="100%" height="100%" controls>
                <source src="static/img/intro3.mp4" type="video/mp4">
              </video>
              <div class="des">
                <span>Premium  15 day pack </span>
                <h5>unlimited 15 days</h5>
                <div class="star">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <h4>Rs. 296</h4>
                <a href="{{url_for('auth.watchvideo')}}"><button type="submit" class="btnsmall">Watch Now</button></a>
              </div>
            </div>
          </div>
          <!-- End content-box -->
                 <!-- Repeat the above content-box structure for each item -->
        <div class="container">
          <div class="content-box">
            <div class="pro">
              <video width="100%" height="100%" controls>
                <source src="static/img/intro3.mp4" type="video/mp4">
              </video>
              <div class="des">
                <span>Land</span>
                <h5>2 Anna 6 ropani</h5>
                <div class="star">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <h4>Rs. 29 lakh</h4>
                <a href="{{url_for('auth.watchvideo')}}"><button type="submit" class="btnsmall">Watch Now</button></a>
              </div>
            </div>
          </div>

        
          <!-- End content-box -->
                 <!-- Repeat the above content-box structure for each item -->
        <div class="container">
          <div class="content-box">
            <div class="pro">
              <video width="100%" height="100%" controls>
                <source src="static/img/intro3.mp4" type="video/mp4">
              </video>
              <div class="des">
                <span>Land</span>
                <h5>2 Anna 6 ropani</h5>
                <div class="star">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
                <h4>Rs. 29 lakh</h4>
                <a href="{{url_for('auth.watchvideo')}}"><button type="submit" class="btnsmall">Watch Now</button></a>
              </div>
            </div>
          </div>
          <!-- End content-box -->
         
      </div>
    </div>
    
      

  </div>
</section>

<div class="livesection">
 
  <div class="live-video-container">

    <h4 class="viewer">2.6k</h4>
    <h1 ><b>Enojoy Live stream ! with Us</b></h1>
    <i class="fa-solid fa-eye"></i>
    <h4>live</h4>
    <a href="{{url_for('auth.live')}}"><butoon type="submit" class="livebtn">Watch Now</butoon></a>
     
    <video src="/static/img/intro.mp4" loop muted autoplay controls width="100%" height="400px" frameborder="0" allowfullscreen ></video>
    
<div class="upcomingevent">

  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="/static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>

  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>

  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>

  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>

  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>

  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>
  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>
  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>
  <div class="upcoming-container">
    <video width="100%" height="100%" controls>
      <source src="static/img/intro3.mp4" type="video/mp4">
    </video>
    
    <h3>Long Jump</h3>
    <span>Date: 525555</span>
    <button class="btnupcoming">Get entry</button>
   <h5 class="text1">$10.00-$25.00</h5> 

  </div>
</div>

  </div>
</div>
{% endblock %}

website/templates/login.html
    {% extends 'roshannav.html' %}
    {% block title %} Userlogin{% endblock %}
    {% block content %}
   
    <style>
        body {
            margin: 0;
            padding: 0;
            overflow: hidden; /* Hide scrollbar when video is playing */
            background-color: #333;
        }

       
        .header,
        .form-container {
            position: relative;
            z-index: 1; /* Bring these elements above the video */
        }

        .form-container {
            padding: 46px;
            margin-top: -80px;
            margin-left: -100px;
        }
        .message{
        z-index: 1000;
      }
      .login-link {
    display: inline-block;
    padding: 10px 20px;
    background-color: #4CAF50; /* Green background color */
    color: white; /* White text color */
    text-decoration: none; /* Remove underline */
    border-radius: 5px; /* Rounded corners */
    border: 2px solid #4CAF50; /* Green border */
    transition: all 0.3s ease; /* Smooth transition effect */
    margin-left: 690px;
    margin-top: 20px;
}

.login-link:hover {
    background-color: white; /* Change background color on hover */
    color: #4CAF50; /* Change text color on hover */
    border-color: #4CAF50; /* Change border color on hover */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Add shadow on hover */
}

    </style>
    <title>Register Page</title>
</head>
<body>

      

    <div class="header">
        <!-- Your header content here -->
    </div>
    <div class="message">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" id="flash-message">
                {{ message }}
                <span class="close-icon" onclick="hideMessage(this)">X</span>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
      
    <section class="form-container">
        <!-- Your form content here -->
        <form method="post" action="{{ url_for('auth.loginn') }}" style="background-color: bisque;">
            <h1 style="color: black;">User Login</h1>
            {% if error %}
                <p style="color: red;">{{ error }}</p>
            {% endif %}
            <div class="input-field">
                
                <input type="email" name="email" style="color: black; background-color: white; border: 1px solid black;" placeholder="Enter your email" required>
            </div>
            <div class="input-field">
               
                <input type="password" name="password" style="color: black; background-color: white; border: 1px solid black;" placeholder="Your password" required>
            </div>
            <input type="submit" name="submit-btn" value="Login" class="btns">
            <p style="color: black;">New User? <a href="{{ url_for('auth.register') }}">Register</a></p>
            
        </form>
        
        

    </section>

{% endblock %}

website/templates/radmindashboard.html
{% extends 'adminnav.html' %}
    {% block title %} Dashboard {% endblock %}
    {% block content %}
<style>

.dashcard{
    display: flex;
    flex-wrap: wrap;
    overflow: hidden;
    height: 120px;
    align-items: center;
    margin-left: 30px;
    gap: 15px; 
}

.card{
   padding: 10px; 
}

</style>
 <section style="z-index: 1000; margin-top: 200px;" class="dashcard">  
<div class="card" style="width: 18rem; z-index: 1000; border: 1px solid whitesmoke;">
    <div class="card-body" style="z-index: 1000;">
      <h1 class="card-title" style="z-index: 1000; font-size: 50px; color: blue;">7</h1>
      <p class="card-text">Total User</p>
      <i class="fa-solid fa-user" style="margin-right: 12px; margin-left: 170px;"></i><a href="{{url_for('auth.admintable')}}" class=" btn-primary" style="color: red;">See User</a><i class="fa-solid fa-arrow-right" style="margin-left: 15px;"></i>
    </div>
  </div>

  <div class="card" style="width: 18rem; z-index: 1000; border: 1px solid whitesmoke;">
    <div class="card-body" style="z-index: 1000;">
      <h1 class="card-title" style="z-index: 1000; font-size: 50px; color: blue;">3</h1>
      <p class="card-text">Ongoing Live</p>
      <i class="fa-solid fa-camera" style="margin-right: 12px; margin-left: 170px; "></i><a href="{{url_for('auth.live')}}" class=" btn-primary" style="color: red;">Go Live</a><i class="fa-solid fa-arrow-right" style="margin-left: 15px;"></i>
    </div>
  </div>


  <div class="card" style="width: 18rem; z-index: 1000; border: 1px solid whitesmoke;">
    <div class="card-body" style="z-index: 1000;">
      <h1 class="card-title" style="z-index: 1000; font-size: 50px; color: blue;">4</h1>
      <p class="card-text">Total Highlits</p>
      <i class="fa-solid fa-highlighter" style="margin-right: 12px; margin-left: 160px;"></i><a href="#" class=" btn-primary" style="color: red;">Highlights</a><i class="fa-solid fa-arrow-right" style="margin-left: 15px;"></i>
    </div>
  </div>

  <div class="card" style="width: 18rem; z-index: 1000; border: 1px solid whitesmoke;">
    <div class="card-body" style="z-index: 1000;">
      <h1 class="card-title" style="z-index: 1000; font-size: 50px; color: blue;">14</h1>
      <p class="card-text">New Schedule</p>
      <i class="fa-regular fa-clock" style="margin-right: 12px; margin-left: 170px;"></i><a href="#" class=" btn-primary" style="color: red;">Schedule</a><i class="fa-solid fa-arrow-right" style="margin-left: 15px;"></i>
    </div>
  </div>
</section> 
    {% endblock %}